### ISSUE TITLE
Problem with python 3.12

### ISSUE THREAD

**Issue by matclab** [TyberiusPrime/i3-instant-layout#15]
I've some difficuties when installing i3-instant-layout  with python 3.12:
```
Traceback (most recent call last):
  File "/home/clabaut/.virtualenvs/i3il/bin/i3-instant-layout", line 5, in <module>
    from i3_instant_layout.main import main
  File "/home/clabaut/.virtualenvs/i3il/lib/python3.12/site-packages/i3_instant_layout/__init__.py", line 2, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by TyberiusPrime** [comment]
I've pushed a new release that will fix this. Give the CI a couple o minutes to push  0.1.12 to pypi and you should be good to go.
