### ISSUE TITLE
'Con' object has no attribute 'ipc_data'

### ISSUE THREAD

**Issue by eater** [TyberiusPrime/i3-instant-layout#5]
I have 4 windows in a split layout. I call `i3-instant-layout 2c` in a terminal (which is one of the 4 windows). It tells me:

```
Traceback (most recent call last):
  File "/home/eater/.local/bin/i3-instant-layout", line 8, in <module>
    sys.exit(main())
  File "/home/eater/.local/lib/python3.6/site-packages/i3_instant_layout/main.py", line 226, in main
    nuke_swallow_windows()
  File "/home/eater/.local/lib/python3.6/site-packages/i3_instant_layout/main.py", line 39, in nuke_swallow_windows
    walk_tree(tree)
  File "/home/eater/.local/lib/python3.6/site-packages/i3_instant_layout/main.py", line 32, in walk_tree
    if con.ipc_data.get("swallows", False):
AttributeError: 'Con' object has no attribute 'ipc_data'
```

**Comment by TyberiusPrime** [comment]
What version of i3-py do you have installed? How did you install?

**Comment by eater** [comment]
According to pip,`i3-py in /home/eater/.local/lib/python3.6/site-packages (0.6.4)`

**Comment by dieggywegz** [comment]
I'm experiencing this exact same issue. Have you figured out any fix? Let me know if I can give any more info.

**Comment by tott** [comment]
Seeing the same here i3-py-0.6.4 and i3-gaps version 4.19-54-g4791b221

**Comment by tott** [comment]
Quick update - I had to get i3ipc to version 2.2.1 and things worked fine

**Comment by TyberiusPrime** [comment]
Ok, I've set a minimum version.
